[CSV DATA PROCESSING]
# parameters used by the csv_handler library
Min_Number_Satellites = 12
Max_Number_Satellites = 20

[HEART RATE]
# Heart Rate parameters used by the workload_metrics_calculator library
HR_resting = 65