# ---- GENERAL SETTINGS FOR OPTIZONE REPORT PROJECT ----
# < IMPORTANT NOTICE FOR PARAMETERS BELOW >
# 1) Dataset_File_Name: stored in /data_samples directory - contains athlete's GPS & HR data session
# 2) show_..._... : to enable/disable showing corresponding metrics - use YES/NO only
[GENERAL REPORT SETTINGS]
; Dataset_File_Name = GPS_Sample_downsampled_light.csv
Dataset_File_Name = GPS_Sample.csv
show_GPS_metrics = YES
show_HR_metrics = YES
show_Fitness_metrics = YES
show_Pitch_Positions = YES
show_Pitch_Heatmap = YES
# --- --- --- --- --- --- --- --- --- --- --- --- --- ---

# ---- PARAMETERS FOR CSV DATA PROCESSING ----
# < IMPORTANT NOTICE FOR PARAMETERS BELOW >
# 1) min_Number_Satellites: data below this threshold will be deleted in the processing section
# 2) min_Quality_of_Signal: data below this threshold will be deleted in the processing section
[CSV DATA PROCESSING]
min_Number_Satellites = 12
min_Quality_of_Signal = 150
# --- --- --- --- --- --- --- --- --- --- --- --- --- ---

# ---- PARAMETERS FOR ATHLETE'S PERSONAL INFORMATION ----
# < IMPORTANT NOTICE FOR PARAMETERS BELOW >
# 1) Resting_HR: athlete's resting heart rate to be measured in BPM
# 2) Athlete_Age: athlete's current age in years
[ATHLETE PERSONAL INFORMATION]
Resting_HR = 60
Athlete_Age = 23
# --- --- --- --- --- --- --- --- --- --- --- --- --- ---

# ---- PARAMETERS FOR PITCH CORNERS GPS COORDINATES ----
# < IMPORTANT NOTICE FOR PARAMETERS BELOW >
# 1) Lat_..._... : latitude of the 4 pitch corners in degrees (ex: 46.219117)
# 2) Lon_..._... : longitude of the 4 pitch corners in degrees (ex: 6.082403)
[PITCH GPS COORDINATES]
Lat_Bottom_Left = 46.219117
Lon_Bottom_Left = 6.082403
Lat_Bottom_Right = 46.219790
Lon_Bottom_Right = 6.083261
Lat_Top_Right = 46.220172
Lon_Top_Right = 6.082642
Lat_Top_Left = 46.219500
Lon_Top_Left = 6.081783
# --- --- --- --- --- --- --- --- --- --- --- --- --- ---

# ---- PARAMETERS FOR MOVING SPEED THRESHOLDS IN METRICS COMPUTATION ----
# < IMPORTANT NOTICE FOR PARAMETERS BELOW >
# 1) ..._..._speed_threshold : moving intensity speed threshold used in metrics computation (in m/s)
[MOVING INTENSITY THRESHOLDS]
Stopped_Moving_speed_threshold = 0.9
Walking_speed_threshold = 1.94
Jogging_speed_threshold = 3.89
Running_speed_threshold = 5.50
Sprinting_speed_threshold = 6.94
# --- --- --- --- --- --- --- --- --- --- --- --- --- ---